services:
  instube-bot:
    build: .
    container_name: instube-downloader-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/.venv
      - ./cookies.txt:/app/cookies.txt
